### ISSUE TITLE
Wrapping label text on y-axis

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/cgov-chart-data#12]
### Issue description
*Label text sometimes shows up inconsistently as being wrapped or unwrapped*

> **ESTIMATE** 1

Link to issue: https://github.com/NCIOCPL/cgov-digital-platform/issues/3830

### What's the expected result?
- Label text should show up unwrapped

### What's the actual result?
- Label text sometimes shows up as wrapped or unwrapped

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
Looks good on ODE 702. Thanks @seyilonge-nci 
cc: @KateMashkinaNIH
